lab9/urls.py
from django.urls import path, include
from . import views

app_name='lab9'
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('accounts/', include('django.contrib.auth.urls')), 
]

ppw3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab9.urls')),
]

lab9/models.py
from django.db import models

# Create your models here.

lab9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'username',
        'placeholder':'Put your account name here',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id':'name',
        'placeholder':'Put your name here',
    }
    email_attrs = {
        'type': 'email',
        'class': 'form-control',
        'id':'email',
        'placeholder':"Optional",
    }
    password1_attrs = {
        'type': 'password',
        'class': 'form-control',
        'id':'password1',
    }
    password2_attrs = {
        'type': 'password',
        'class': 'form-control',
        'id':'password2',
    }

    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs=username_attrs))
    name = forms.CharField(label='Name ', max_length=30, required=True, widget=forms.TextInput(attrs=name_attrs))
    email = forms.CharField(label='Email ', max_length=30, required=False, widget=forms.TextInput(attrs=email_attrs))
    password1 = forms.CharField(label='Password ', widget=forms.PasswordInput(attrs=password1_attrs))
    password2 = forms.CharField(label='Password confirmation ', widget=forms.PasswordInput(attrs=password2_attrs), help_text= 'Enter the same password as above, for verification.')

    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'password1', 'password2', )

lab9/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.urls import reverse
from . import forms, urls

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return render(request, 'lab9/index.html', {'user_login' : request.user.username})
    return render(request, 'lab9/index.html', {'user_login' : 'user'})

def register(request):
    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'lab9/index.html', {'user_login' : username})
    else:
        form = forms.RegisterForm()
    return render(request, 'lab9/register.html', {'form_register': form})

lab9/templates/lab9/base.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <!-- JQuerry-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Static File CSS-->
    <link rel="stylesheet" href="{% static 'lab9/css/lab9.css' %}"> 
    <link rel="stylesheet" href="{% static 'lab9/css/bootstrap.css' %}">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Jquery CSS-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Static File JS-->
    <script src="{% static 'lab9/js/lab9.js' %}"></script>

    <!-- Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Jquery JS-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
    <nav class="main-theme navbar navbar-light navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'lab9:index' %}">
                <img src="{% static 'lab9/images/ProfilePicture.JPG' %}" class="rounded-circle" width="75" height="75" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab9:index' %}">Hello {{ user_login }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab9:logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab9:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab9:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
                <button class="nav-link btn my-2 my-sm-0" id="change_theme"></button>
            </div>
        </div>
    </nav>

    <main>
    {% block content %}
    {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="main-theme page-footer navbar-static-bottom font-small pt-4">

        <!-- Footer Links -->
        <div class="container text-center text-md-left">

            <!-- Grid row -->
            <div class="row d-flex align-items-center">

                <!-- Grid column -->
                <div class="col-md-7 col-lg-8">

                    <!--Copyright-->
                    <p class="text-center text-md-left">© 2019 Copyright: Randy Desnantara
                    </p>

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-5 col-lg-4 ml-lg-0">

                    <!-- Social buttons -->
                    <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://www.instagram.com/randydesnantara/">
                                <img src="{% static 'lab9/images/Instagram.png' %}" width="25" height="25" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://twitter.com/Randyptr">
                                <img src="{% static 'lab9/images/Twitter.png' %}" width="25" height="25" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1" href="https://www.youtube.com/channel/UCrQRbEk69hs4z145S2WMcdQ?view_as=subscriber">
                                <img src="{% static 'lab9/images/Youtube.png' %}" width="25" height="25"    alt="">
                            </a>
                        </li>
                    </ul>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->

    </footer>
<!-- Footer -->
</body>
</html>

lab9/templates/lab9/index.html
{% extends 'lab9/base.html' %}
{% load static %}

{% block title %}Homescreen{% endblock %}

{% block content %}
<style>
    body {
        background-image: url( "{% static 'lab9/images/RinjaniSunriseRandy.jpeg' %}" );
        background-size: cover; 
        height: 100%;
    }
</style>

<div class="container pt-5 pb-5">
    <div class="card mx-auto transparent-bg-gray" style="width: 100%;">
        <div class="card-body">
            <p class="card-text big-text">Welcome to my site, dear {{ user_login }}<br>
            <br>
            I am Randy<br>
            <br>
            Nothing but just a humble newbee front-end/back-end developer<br>
            Please continue to explore it<br>
            {% if user.is_authenticated %}
            {% else %}
                <br>
                For more access
                <a class="btn btn-outline-primary" href="{% url 'lab9:register' %}">Register Here</a>
            {% endif %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

lab9/templates/lab9/register.html
{% extends 'lab9/base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container pt-5 pb-5">
    <div class="container transparent-bg-gray pb-3 pt-3 rounded mx-auto">
        <div class="big-text pb-1">Register</div>
        <form id="form_register" method="POST">
            {% csrf_token %}    
            <div class="form-group">
                {{ form_register }} 
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>	
    </div>
</div>
{% endblock %}